module.exports = {
    offices:[
        {
            id:0,
            researcher:"_Home"
        },
        {
            id:1,
            researcher:"Buche"
        },
        {
            id:2,
            researcher:"Gaubert"
        },
        {
            id:3,
            researcher:"Kubicki"
        }
    ],

    arks:[
        {
            researcher1:"_Home",
            researcher2:"Buche",
			direction1:3,
			direction2:1,
			moves:[
				{
					move:"forward",
					duration:500,
					speed:50
				}
			]
        },
        {
            researcher1:"Buche",
            researcher2:"Kubicki",
			direction1:0,
			direction2:2,
			moves:[
				{
					move:"forward",
					duration:600,
					speed:50
				}
			]
        },
        {
            researcher1:"_Home",
            researcher2:"Gaubert",
			direction1:0,
			direction2:2,
			moves:[
				{
					move:"forward",
					duration:500,
					speed:50
				}
			]
        },
        {
            researcher1:"Gaubert",
            researcher2:"Kubicki",
			direction1:3,
			direction2:1,
			moves:[
				{
					move:"forward",
					duration:500,
					speed:50
				}
			]
        }
    ]
};
